export const UnknownUsersTypes = {
  SET_LOAD_STORE_UNKNOWN_USERS: "SET_LOAD_STORE_UNKNOWN_USERS",
  SET_ITEM_PER_PAGE_UNKNOWN: "SET_ITEM_PER_PAGE_UNKNOWN",
  SET_COUNT_UNKNOWN_USERS: "SET_COUNT_UNKNOWN_USERS",
  SET_MORE_UNKNOWN_USERS: "SET_MORE_UNKNOWN_USERS",
};
