export const AllUsersTypes = {
  SET_LOAD_STORE_ALL_USERS: "SET_LOAD_STORE_ALL_USERS",
  SET_ITEM_PER_PAGE: "SET_ITEM_PER_PAGE",
  SET_COUNT_ALL_USERS: "SET_COUNT_ALL_USERS",
  SET_MORE_ALL_USERS: "SET_MORE_ALL_USERS",
  SET_STATE_USERS: "SET_STATE_USERS",
};
