export const DeadUsersTypes = {
  SET_LOAD_STORE_DEAD_USERS: "SET_LOAD_STORE_DEAD_USERS",
  SET_ITEM_PER_PAGE_DEAD: "SET_ITEM_PER_PAGE_DEAD",
  SET_COUNT_DEAD_USERS: "SET_COUNT_DEAD_USERS",
  SET_MORE_DEAD_USERS: "SET_MORE_DEAD_USERS",
};
