export const AliveUsersTypes = {
  SET_LOAD_STORE_ALIVE_USERS: "SET_LOAD_STORE_ALIVE_USERS",
  SET_ITEM_PER_PAGE_ALIVE: "SET_ITEM_PER_PAGE_ALIVE",
  SET_COUNT_ALIVE_USERS: "SET_COUNT_ALIVE_USERS",
  SET_MORE_ALIVE_USERS: "SET_MORE_ALIVE_USERS",
};
